language: r
dist: bionic
cache: packages

# Per package values
env:
  global:
    - ALLOWED_NOTES=1
    - NO_IMPORTS=0

# Generic
notifications:
  email:
    recipients:
     - alerts+travis@jumpingrivers.support
    on_success: change
    on_failure: change

r_binary_packages:
  - rstan

apt_packages:
  - libnode-dev
  - python3
  - python3-pip
 
# Generic + Bespoke
# 1. Only needed for jrNotes
# 2. Rcpp bugs. On next update of Rcpp CRAN, delete line 2
before_install: |
  Rscript -e 'if (!requireNamespace("Rcpp", quietly = TRUE)) install.packages("Rcpp")'
  wget https://raw.githubusercontent.com/jr-packages/drat/master/options.R &&
  cat options.R >> ~/.Rprofile.site &&
  rm options.R

# Generic
before_script:
  - pip3 install pygments
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/test_deploy.sh
  - if [ ${TRAVIS_PULL_REQUEST} = "false" ] && [ $TRAVIS_BRANCH = "master" ]; then bash test_deploy.sh; fi
  - rm test_deploy.sh

# Generic
script:
  - Rscript -e "source('https://raw.githubusercontent.com/jr-packages/drat/master/script.R')"
  - Rscript -e "rmarkdown::render('inst/extdata/mwe.Rmd')"

# Generic
# May delete line depending on testing
after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && Rscript -e 'covr::codecov()'
